[project]
name = "central"
version = "0.1.0"
description = "Dolphin's CI/CD plumbing infrastructure"
authors = [{ name = "Pierre Bourdon", email = "delroth@dolphin-emu.org" }]
maintainers = [{ name = "OatmealDome", email = "oatmeal@dolphin-emu.org" }]
requires-python = ">=3.13,<3.14"
readme = "README.md"
license = "MIT"
dependencies = [
    "pyyaml~=6.0.3",
    "pypeul",
    "bottle>=0.13.4,<0.14",
    "requests>=2.34.2,<3",
    "pycryptodome>=3.23.0,<4",
    "mwclient>=0.11.0,<0.12",
    "jwt>=1.4.0,<2",
    "discord-py>=2.7.1,<3",
]

[project.scripts]
central = "central.__main__:main"

[dependency-groups]
dev = [
    "black>=26.5.1,<27",
    "pytest>=9.1.1,<10",
]

[tool.uv.sources]
pypeul = { git = "https://github.com/dolphin-emu/pypeul", rev = "9ca8f8896e51008f6179ca950152abc50484077f" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
